### ISSUE TITLE
Failed to start Motr cluster 

### ISSUE THREAD

**Issue by lia54** [Seagate/cortx-motr#1130]
Trying to deploy a cortx-motr cluster I got the following error:

2021-10-11 09:26:13: Generating cluster configuration... OK
2021-10-11 09:26:15: Stopping Consul on this node... OK
2021-10-11 09:26:27: Stopping Consul on other nodes... OK
2021-10-11 09:26:27: Starting Consul server on this node........... OK
2021-10-11 09:26:37: Importing configuration into the KV store... OK
2021-10-11 09:26:37: Starting Consul on other nodes...Consul ready on all nodes
2021-10-11 09:26:37: Updating Consul configuraton from the KV store... OK
2021-10-11 09:26:40: Waiting for the RC Leader to get elected..... OK
2021-10-11 09:26:43: Starting Motr (phase1, mkfs)...Job for motr-mkfs@0x7200000000000001:0x9.service failed because the control process exited with error code. See "systemctl status motr-mkfs@0x7200000000000001:0x9.service" and "journalctl -xe" for details.

Checking the journalctl for more details give me this error:
 
ax[102979]: motr[102979]: dd50 ERROR [/root/rpmbuild/BUILD/cortx-motr-2.0.0/net/lnet/ulnet_core.c:1154:nlx_core_tm_st
ax[102979]: motr[102979]: 5400 ERROR [rpc/rpc_machine.c:513:rpc_tm_setup] <! rc=-101 TM start
ax[102979]: motr[102979]: 5400 ERROR [rpc/rpc_machine.c:173:m0_rpc_machine_init] <! rc=-101
ax[102979]: motr[102979]: 57f0 ERROR [ha/halon/interface.c:1024:m0_halon_interface_start] <! rc=-101
ax[102979]: motr[102979]: 5910 ERROR [hax.c:717:start] Failed to start m0_halon_interface
ax[102979]: 2021-10-11 09:14:51,748 [ERROR] {MainThread} Cannot start Motr API. m0_halon_interface::start returned non-z
ax[102979]: 2021-10-11 09:14:51,749 [ERROR] {MainThread} Exiting due to an exception
ax[102979]: Traceback (most recent call last):
ax[102979]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/hax.py", line 146, in main
ax[102979]: profile=cfg.profiles[0])
ax[102979]: File "/opt/seagate/cortx/hare/lib64/python3.6/site-packages/hax/motr/__init__.py", line 89, in start
ax[102979]: raise RuntimeError('Cannot start m0_halon_interface.'
ax[102979]: RuntimeError: Cannot start m0_halon_interface.Please check Motr logs for more details.
ax[102979]: 2021-10-11 09:14:51,750 [INFO] {MainThread} Finalizing motr
kfs[102988]: propagating error to parent shell
d[1]: motr-mkfs@0x7200000000000001:0x9.service: main process exited, code=exited, status=42/n/a

Does anyone know how to solve this issue?

**Comment by cortx-admin** [comment]
This issue has been mirrored in Jira Server: https://jts.seagate.com/browse/EOS-25361

**Comment by nkommuri** [comment]
@lia54 please let us know the hash of the repo cortx-motr that you are using

**Comment by cortx-admin** [comment]
> Papan Kumar Singh commented in Jira Server:

run "hctl bootstrap --mkfs ~/CDF.yaml" and " hctl shutdown" 10 times with the following CDF file

{code:java}
# Cluster Description File (CDF).
# See `cfgen --help-schema` for the format description.

create_aux: false # optional; supported values: "false" (default), "true"
nodes:
  - hostname: ssc-vm-g2-rhev4-1676.colo.seagate.com # [user@]hostname
    data_iface: eth1        # name of data network interface
    #data_iface_type: o2ib  # type of network interface (optional);
                            # supported values: "tcp" (default), "o2ib"
    m0_servers:
      - runs_confd: true
        io_disks:
          data: []
      - io_disks:
          #meta_data: /path/to/meta-data/drive
          data:
            - /dev/loop0
            - /dev/loop1
            - /dev/loop2
            - /dev/loop3
            - /dev/loop4
            - /dev/loop5
            - /dev/loop6
            - /dev/loop7
            - /dev/loop8
            - /dev/loop9
    m0_clients:
      s3: 0         # number of S3 servers to start
      other: 2      # max quantity of other Motr clients this host may have
pools:
  - name: the pool
    type: sns  # optional; supported values: "sns" (default), "dix", "md"
    disk_refs:
      - { path: /dev/loop0, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop1, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop2, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop3, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop4, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop5, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop6, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop7, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop8, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
      - { path: /dev/loop9, node: ssc-vm-g2-rhev4-1676.colo.seagate.com }
    data_units: 1
    parity_units: 0
    spare_units: 0
    #allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
#profiles:
#  - name: default
#    pools: [ the pool ]
#fdmi_filters:
#  - name: test
#    node: localhost
#    client_index: 1
#    substrings: ["Bucket-Name", "Object-Name", "Object-URI"]

{code}


{code:java}
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-26 23:05:46: Generating cluster configuration... OK
2021-10-26 23:05:48: Starting Consul server on this node........ OK
2021-10-26 23:05:54: Importing configuration into the KV store... OK
2021-10-26 23:05:55: Starting Consul on other nodes...Consul ready on all nodes
2021-10-26 23:05:55: Updating Consul configuraton from the KV store... OK
2021-10-26 23:05:57: Waiting for the RC Leader to get elected....... OK
2021-10-26 23:06:02: Starting Motr (phase1, mkfs)... OK
2021-10-26 23:06:11: Starting Motr (phase1, m0d)... OK
2021-10-26 23:06:14: Starting Motr (phase2, mkfs)... OK
2021-10-26 23:06:27: Starting Motr (phase2, m0d)... OK
2021-10-26 23:06:31: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
You have new mail in /var/spool/mail/root
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 21:46:33: Generating cluster configuration... OK
2021-10-27 21:46:35: Starting Consul server on this node........ OK
2021-10-27 21:46:43: Importing configuration into the KV store... OK
2021-10-27 21:46:44: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 21:46:44: Updating Consul configuraton from the KV store... OK
2021-10-27 21:46:48: Waiting for the RC Leader to get elected........ OK
2021-10-27 21:46:54: Starting Motr (phase1, mkfs)... OK
2021-10-27 21:47:04: Starting Motr (phase1, m0d)... OK
2021-10-27 21:47:08: Starting Motr (phase2, mkfs)... OK
2021-10-27 21:47:23: Starting Motr (phase2, m0d)... OK
2021-10-27 21:47:31: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 21:52:50: Generating cluster configuration... OK
2021-10-27 21:52:54: Starting Consul server on this node........ OK
2021-10-27 21:53:01: Importing configuration into the KV store... OK
2021-10-27 21:53:02: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 21:53:03: Updating Consul configuraton from the KV store... OK
2021-10-27 21:53:07: Waiting for the RC Leader to get elected...... OK
2021-10-27 21:53:12: Starting Motr (phase1, mkfs)... OK
2021-10-27 21:53:23: Starting Motr (phase1, m0d)... OK
2021-10-27 21:53:27: Starting Motr (phase2, mkfs)... OK
2021-10-27 21:53:44: Starting Motr (phase2, m0d)... OK
2021-10-27 21:53:50: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 21:54:39: Generating cluster configuration... OK
2021-10-27 21:54:42: Starting Consul server on this node....... OK
2021-10-27 21:54:48: Importing configuration into the KV store... OK
2021-10-27 21:54:49: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 21:54:50: Updating Consul configuraton from the KV store... OK
2021-10-27 21:54:55: Waiting for the RC Leader to get elected..... OK
2021-10-27 21:54:58: Starting Motr (phase1, mkfs)... OK
2021-10-27 21:55:09: Starting Motr (phase1, m0d)... OK
2021-10-27 21:55:13: Starting Motr (phase2, mkfs)... OK
2021-10-27 21:55:28: Starting Motr (phase2, m0d)... OK
2021-10-27 21:55:35: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 21:56:57: Generating cluster configuration... OK
2021-10-27 21:57:01: Starting Consul server on this node.......... OK
2021-10-27 21:57:10: Importing configuration into the KV store... OK
2021-10-27 21:57:11: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 21:57:11: Updating Consul configuraton from the KV store... OK
2021-10-27 21:57:15: Waiting for the RC Leader to get elected.... OK
2021-10-27 21:57:16: Starting Motr (phase1, mkfs)... OK
2021-10-27 21:57:27: Starting Motr (phase1, m0d)... OK
2021-10-27 21:57:30: Starting Motr (phase2, mkfs)... OK
2021-10-27 21:57:47: Starting Motr (phase2, m0d)... OK
2021-10-27 21:57:52: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 22:14:35: Generating cluster configuration... OK
2021-10-27 22:14:38: Starting Consul server on this node........ OK
2021-10-27 22:14:45: Importing configuration into the KV store... OK
2021-10-27 22:14:46: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 22:14:46: Updating Consul configuraton from the KV store... OK
2021-10-27 22:14:50: Waiting for the RC Leader to get elected....... OK
2021-10-27 22:14:57: Starting Motr (phase1, mkfs)... OK
2021-10-27 22:15:09: Starting Motr (phase1, m0d)... OK
2021-10-27 22:15:12: Starting Motr (phase2, mkfs)... OK
2021-10-27 22:15:28: Starting Motr (phase2, m0d)... OK
2021-10-27 22:15:35: Checking health of services... OK
You have new mail in /var/spool/mail/root
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 22:17:41: Generating cluster configuration... OK
2021-10-27 22:17:44: Starting Consul server on this node......... OK
2021-10-27 22:17:54: Importing configuration into the KV store... OK
2021-10-27 22:17:55: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 22:17:56: Updating Consul configuraton from the KV store... OK
2021-10-27 22:18:00: Waiting for the RC Leader to get elected........ OK
2021-10-27 22:18:08: Starting Motr (phase1, mkfs)... OK
2021-10-27 22:18:18: Starting Motr (phase1, m0d)... OK
2021-10-27 22:18:23: Starting Motr (phase2, mkfs)... OK
2021-10-27 22:18:42: Starting Motr (phase2, m0d)... OK
2021-10-27 22:18:49: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 22:44:43: Generating cluster configuration... OK
2021-10-27 22:44:47: Starting Consul server on this node........... OK
2021-10-27 22:44:57: Importing configuration into the KV store... OK
2021-10-27 22:44:58: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 22:44:59: Updating Consul configuraton from the KV store... OK
2021-10-27 22:45:03: Waiting for the RC Leader to get elected......... OK
2021-10-27 22:45:12: Starting Motr (phase1, mkfs)... OK
2021-10-27 22:45:29: Starting Motr (phase1, m0d)... OK
2021-10-27 22:45:33: Starting Motr (phase2, mkfs)... OK
2021-10-27 22:45:48: Starting Motr (phase2, m0d)... OK
2021-10-27 22:45:54: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 23:28:39: Generating cluster configuration... OK
2021-10-27 23:28:43: Starting Consul server on this node......... OK
2021-10-27 23:28:51: Importing configuration into the KV store... OK
2021-10-27 23:28:52: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 23:28:52: Updating Consul configuraton from the KV store... OK
2021-10-27 23:28:56: Waiting for the RC Leader to get elected...... OK
2021-10-27 23:29:00: Starting Motr (phase1, mkfs)... OK
2021-10-27 23:29:10: Starting Motr (phase1, m0d)... OK
2021-10-27 23:29:15: Starting Motr (phase2, mkfs)... OK
2021-10-27 23:29:32: Starting Motr (phase2, m0d)... OK
2021-10-27 23:29:39: Checking health of services... OK
You have new mail in /var/spool/mail/root
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]# hctl bootstrap --mkfs ~/CDF.yaml
2021-10-27 23:30:22: Generating cluster configuration... OK
2021-10-27 23:30:25: Starting Consul server on this node........... OK
2021-10-27 23:30:36: Importing configuration into the KV store... OK
2021-10-27 23:30:37: Starting Consul on other nodes...Consul ready on all nodes
2021-10-27 23:30:38: Updating Consul configuraton from the KV store... OK
2021-10-27 23:30:43: Waiting for the RC Leader to get elected....... OK
2021-10-27 23:30:49: Starting Motr (phase1, mkfs)... OK
2021-10-27 23:30:58: Starting Motr (phase1, m0d)... OK
2021-10-27 23:31:02: Starting Motr (phase2, mkfs)... OK
2021-10-27 23:31:18: Starting Motr (phase2, m0d)... OK
2021-10-27 23:31:24: Checking health of services... OK
[root@ssc-vm-g2-rhev4-1676 ~]# hctl shutdown
Stopping m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0xc (ios) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped m0d@0x7200000000000001:0x9 (confd) at ssc-vm-g2-rhev4-1676.colo.seagate.com
Stopping hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-hax at ssc-vm-g2-rhev4-1676.colo.seagate.com
Making sure that RC leader can be re-elected next time
Stopping hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com...
Stopped hare-consul-agent at ssc-vm-g2-rhev4-1676.colo.seagate.com
Shutting down RC Leader at ssc-vm-g2-rhev4-1676.colo.seagate.com...
[root@ssc-vm-g2-rhev4-1676 ~]#

{code}

**Comment by cortx-admin** [comment]
> Papan Kumar Singh commented in Jira Server:

Verified with the code of git commit hash 0a58ae5a7a8a8b65f7e74c75cd2aa4e9a20d5510. 
Successfully created cluster.

**Comment by cortx-admin** [comment]
> Papan Kumar Singh commented in Jira Server:

Able to create cluster

**Comment by cortx-admin** [comment]
> Papan Kumar Singh commented in Jira Server:

Closing as issue is not recreateable

**Comment by cortx-admin** [comment]
> Papan Kumar Singh commented in Jira Server:

with git source code of hash 0a58ae5a7a8a8b65f7e74c75cd2aa4e9a20d5510
cluster is up.
