### ISSUE TITLE
be-ut:tx_bulk-large_all fails with: panic: (ld_start_tlist_is_empty(&ld->lds_start_q)) at be_log_discard_flush_finished()

### ISSUE THREAD

**Issue by nikitadanilov** [Seagate/cortx-motr#1660]
### Problem

```
be-ut:tx_bulk-large_all fails intermittently:

$ ./utils/m0run -dgdb m0ut -- -tbe-ut:tx_bulk-large_all -n1000
...
START Iteration: 8 out of 1000
be-ut
  tx_bulk-large_all  motr[952092]:  5ab0  FATAL  [lib/assert.c:50:m0_panic]  panic: (ld_start_tlist_is_empty(&ld->lds_start_q)) at be_log_discard_flush_finished() (be/log_discard.c:182)  [git: 2.0.0-670-44-g9456562c-dirty] /mnt/scratch/varmotr/m0ut/m0trace.952092
Motr panic: (ld_start_tlist_is_empty(&ld->lds_start_q)) at be_log_discard_flush_finished() be/log_discard.c:182 (errno: 4) (last failed: none)
...
(gdb) bt
#0  0x00007fffe99ba38f in raise () from /lib64/libc.so.6
#1  0x00007fffe99a4dc5 in abort () from /lib64/libc.so.6
#2  0x00007fffebdb7fa0 in m0_arch_panic (c=0x7fffec2b7740 <__pctx.7463>, ap=0x7fffdb7f5b48) at lib/user_space/uassert.c:131
#3  0x00007fffebd982e8 in m0_panic (ctx=0x7fffec2b7740 <__pctx.7463>) at lib/assert.c:52
#4  0x00007fffebc5423a in be_log_discard_flush_finished (ld=0xf315e8) at be/log_discard.c:182
#5  0x00007fffebc547f9 in be_log_discard_ast (grp=0x76ae90, ast=0xf31af0) at be/log_discard.c:281
#6  0x00007fffebec0bce in m0_sm_asts_run (grp=0x76ae90) at sm/sm.c:173
#7  0x00007fffebec0800 in m0_sm_group_lock (grp=0x76ae90) at sm/sm.c:86
#8  0x00007fffebda11b2 in locs_ast_handler (__unused=0x0) at lib/locality.c:198
#9  0x00007fffebda58c8 in m0_thread_trampoline (arg=0x76af68) at lib/thread.c:117
#10 0x00007fffebdb9617 in uthread_trampoline (arg=0x76af68) at lib/user_space/uthread.c:98
#11 0x00007fffeb39815a in start_thread () from /lib64/libpthread.so.0
#12 0x00007fffe9a7fdd3 in clone () from /lib64/libc.so.6
(gdb) up 4
#4  0x00007fffebc5423a in be_log_discard_flush_finished (ld=0xf315e8) at be/log_discard.c:182
182		M0_PRE(ld_start_tlist_is_empty(&ld->lds_start_q));
(gdb) p ld->lds_start_q
$1 = {t_magic = 56891501707639, t_head = {l_head = 0x12fd2c0, l_tail = 0x12fd540}}
(gdb) p &ld->lds_start_q
$2 = (struct m0_tl *) 0xf31700
(gdb) p/x &((struct m0_be_log_discard_item *)0)->ldi_start_link
$3 = 0x60
(gdb) p/x *((struct m0_be_log_discard_item *)((unsigned)ld->lds_start_q.t_head.l_head - 0x60))
$4 = {ldi_ld = 0xf315e8, ldi_state = 0x2, ldi_user_data = 0xf2e558, ldi_time_start = 0x16e7f5dab7af72f5, ldi_time_finish = 0x16e7f5dab7fcb688,
  ldi_synced = 0x0, ldi_ext = {e_header = {hd_magic = 0x0, hd_bits = 0x0}, e_start = 0x2d922000, e_end = 0x2e3f0000, e_footer = {ft_magic = 0x0,
      ft_checksum = 0x0}}, ldi_start_link = {t_link = {ll_next = 0x12fd540, ll_prev = 0xf31708}}, ldi_magic = 0x33feedf11e577, ldi_pool_item = {
    bpli_link = {t_link = {ll_next = 0x12fd558, ll_prev = 0xf316b8}}, bpli_magic = 0x33addbec1a5577, bpli_pool_magic = 0x33f100db10b77},
  ldi_pool_magic = 0x33f100db10b77}
(gdb) p/x *((struct m0_be_log_discard_item *)((unsigned)ld->lds_start_q.t_head.l_head.ll_next - 0x60))
$5 = {ldi_ld = 0xf315e8, ldi_state = 0x2, ldi_user_data = 0xf2e558, ldi_time_start = 0x16e7f5dab8911000, ldi_time_finish = 0x16e7f5dab895a749,
  ldi_synced = 0x0, ldi_ext = {e_header = {hd_magic = 0x0, hd_bits = 0x0}, e_start = 0x2e3f0000, e_end = 0x2e3f2000, e_footer = {ft_magic = 0x0,
      ft_checksum = 0x0}}, ldi_start_link = {t_link = {ll_next = 0xf31708, ll_prev = 0x12fd2c0}}, ldi_magic = 0x33feedf11e577, ldi_pool_item = {
    bpli_link = {t_link = {ll_next = 0xf316b8, ll_prev = 0x12fd2d8}}, bpli_magic = 0x33addbec1a5577, bpli_pool_magic = 0x33f100db10b77},
  ldi_pool_magic = 0x33f100db10b77}
```

### Expected behavior

UT should not fail

### How to reproduce

See above.

### Deployment information

Standard Rocky Linux vm from the lab: ssc-vm-g3-rhev4-0346.colo.seagate.com, ask me for access.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30963. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment]
[Max Medved](https://jts.seagate.com/secure/ViewProfile.jspa?name=520406) expects that [EOS-25005](https://jts.seagate.com/browse/CORTX-25005) will fix this issue - but he has not worked on EOS-26865 - If someone is working on this issue, can refer PR linked to EOS-25005

**Comment by nikitadanilov** [comment]
Related PR: https://github.com/Seagate/cortx-motr/pull/1091

**Comment by andriytk** [comment]
Duplicate of https://github.com/Seagate/cortx-motr/issues/1473

**Comment by andriytk** [comment]
Next step - assign someone to fix it.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~211146],

This will be fixed via [https://github.com/Seagate/cortx-motr/pull/1091] which is in draft state. DTM team member planned to work on it but its not prioritized yet

**Comment by chandradharraval** [comment]
@nikitadanilov - We dont see such issues in CFT testing, Do we want to take https://github.com/Seagate/cortx-motr/pull/1091 PR forward? If yes then do we need and update over and above this patch? Also what testing is required if we decide to go ahead with PR 1091?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
