### ISSUE TITLE
libfabric: endpoint is freed while in use.

### ISSUE THREAD

**Issue by nikitadanilov** [Seagate/cortx-motr#1688]
### Problem

libfab_poller()->libfab_txep_event_check(xep, ...)->libfab_buf_done()->libfab_buf_complete()->m0_net_buffer_event_post()->user-call-back.

The call-back frees the buffer and releases the last reference on the end-point. The end-point is freed. On the return to libfab_txep_event_check() the next iteration of m0_tl_teardown(fab_sndbuf, &txep->fep_sndbuf, fbp) loop crashes.

### Expected behavior

Should not crash.

### How to reproduce

(Non-deterministic).
```
rconfc-ut
  init-fini                                       3.43 sec  262 MiB
  start-stop                                      2.64 sec   83 MiB
  local-conf                                      2.46 sec   82 MiB
  local-load-fail                                 2.51 sec   82 MiB
  start-fail                                      2.83 sec   84 MiB
  fail-abort                                      4.52 sec   82 MiB
  fail-retry-rm  motr[583321]:  aa90  FATAL  [lib/assert.c:50:m0_panic]  panic: (m0_tlist_invariant(d, list)) at m0_tlist_head() (lib/tlist.c:191)  [git: 2.0.0-713-25-g47508cad-dirty] /var/motr/m0ut/m0trace.583321
...
(gdb) bt
#0  0x00007f72ab151290 in m0_debugger_invoke () at lib/user_space/uassert.c:154
#1  0x00007f72ab1513e4 in m0_arch_panic (c=c@entry=0x7f72ab6f5d00 <__pctx.3549>, ap=ap@entry=0x7f7229ffab08) at lib/user_space/uassert.c:129
#2  0x00007f72ab131d47 in m0_panic (ctx=0x7f72ab6f5d00 <__pctx.3549>) at lib/assert.c:52
#3  0x00007f72ab14173a in m0_tlist_head (d=0x7f72ab752040 <fab_sndbuf_tl>, list=0x7f7171ce0ec8) at lib/tlist.c:191
#4  0x00007f72ab141798 in m0_tlist_pop (d=0x7f72ab752040 <fab_sndbuf_tl>, list=0x7f7171ce0ec8) at lib/tlist.c:200
#5  0x00007f72ab1e6e7a in fab_sndbuf_tlist_pop (list=0x7f7171ce0ec8) at net/libfab/libfab.c:217
#6  0x00007f72ab1e8931 in libfab_txep_event_check (txep=0x7f7171ce0db0, aep=0x7f7168b24b70, tm=0x7f721db6d010) at net/libfab/libfab.c:659
#7  0x00007f72ab1e9078 in libfab_poller (tm=0x7f721db6d010) at net/libfab/libfab.c:854
#8  0x00007f72ab13f408 in m0_thread_trampoline (arg=0x7f721db6d018) at lib/thread.c:117
...
(gdb) p *fbp
$2 = {fb_magic = 140125114727120, fb_sndmagic = 140125792163072, fb_htmagic = 6872316419617283935, fb_dummy = {1600085855, 1600085855}, fb_rbd = 0x5f5f5f5f5f5f5f5f, fb_riov = 0x5f5f5f5f5f5f5f5f, fb_mr = {bm_desc = 0x5f5f5f5f5f5f5f5f, bm_mr = 0x5f5f5f5f5f5f5f5f}, fb_dp = 0x5f5f5f5f5f5f5f5f, fb_nb = 0x5f5f5f5f5f5f5f5f, fb_ev_ep = 0x5f5f5f5f5f5f5f5f, fb_txctx = 0x5f5f5f5f5f5f5f5f, fb_linkage = {t_link = {ll_next = 0x5f5f5f5f5f5f5f5f, ll_prev = 0x5f5f5f5f5f5f5f5f}}, fb_snd_link = {t_link = {ll_next = 0x5f5f5f5f5f5f5f5f, ll_prev = 0x5f5f5f5f5f5f5f5f}}, fb_htlink = {hl_link = {t_link = {ll_next = 0x5f5f5f5f5f5f5f5f, ll_prev = 0x5f5f5f5f5f5f5f5f}}}, fb_status = 1600085855, fb_length = 6872316419617283935, fb_wr_cnt = 1600085855, fb_xfer_params = {bxp_loc_sidx = 1600085855, bxp_rem_sidx = 1600085855, bxp_xfer_len = 1600085855, bxp_rem_soff = 1600085855, bxp_loc_soff = 1600085855}, fb_bulk_op = 0x5f5f5f5f5f5f5f5f, fb_state = 1600085855, fb_token = 1600085855}
```

### Deployment information

vm

### Additional information

Tentative solution: acquire and release an additional reference to the end-point while it is being processed by poller. I'll create a patch shortly.

**Comment by nikitadanilov** [comment]
See https://github.com/Seagate/cortx-motr/pull/1699 .

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue closed and corresponding PR is merged now
