### ISSUE TITLE
Any suggestion API documentation to refer for cortx-motr 

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#763]
I am running go bindings for cortx-motr and try to figure out what the code is doing and what the error is all about.

```
-bash-4.2$ ./mkv -ep 192.168.180.137@tcp:12345:4:1 -prof 0x7000000000000001:0x4f -proc 0x7200000000000001:0x29 -hax 192.168.180.137@tcp:12345:1:1 0x7800000000000001:1 ac cc
motr[12076]:  67d0  ERROR  [lib/user_space/uuuid.c:86:m0_node_uuid_string_get]  <! rc=-22 open("/sys/module/m0tr/parameters/node_uuid", O_RDONLY)=-1 errno=2: is m0tr.ko loaded?
motr[12076]:  6830  ERROR  [lib/uuid.c:140:m0_node_uuid_init]  Unable to fetch node UUID string
subsystem libm0 init failed: rc = -22
2021/06/16 01:06:17 mio.go:171: m0_client_init() failed: -22
panic: m0_client_init() failed: -22

goroutine 1 [running]:
log.Panicf(0x514289, 0x1b, 0xc000043e38, 0x1, 0x1)
        /usr/lib/golang/src/log/log.go:358 +0xc5
motr/mio.Init()
        /home/502380/cortx-motr/bindings/go/mio/mio.go:171 +0x586
main.main()
        /home/502380/cortx-motr/bindings/go/mkv/mkv.go:57 +0x47
```

Any documentation I could refer to ? @andriytk

**Comment by andriytk** [comment]
These are Motr errors. You can see a hint of what's going on here:
```
motr[12076]:  67d0  ERROR  [lib/user_space/uuuid.c:86:m0_node_uuid_string_get]  <! rc=-22 open("/sys/module/m0tr/parameters/node_uuid", O_RDONLY)=-1 errno=2: is m0tr.ko loaded?
```
"is m0tr.ko loaded?"

**Comment by kiwionly2** [comment]
I still try to understand how the thing work overall, is cortx-motr required to run on network?  or could PUT/GET on local drive ?

**Comment by andriytk** [comment]
Yes. Even if you run it locally, you might have the local Motr server (single-node cluster) running in order to use KV-index store. Same as with objects, but instead of the object you have an index to which you can put/get key-values.

**Comment by kiwionly2** [comment]
ok thx !
