### ISSUE TITLE
m0d-ios panic: (stob->so_state != CSS_DELETE) at m0_storage_dev_stob_create() 

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#769]
At the SAGE prototype cluster:

```
$ sudo systemctl status m0d@0x7200000000000001:0x25 -n 20 -l
● m0d@0x7200000000000001:0x25.service - m0d helper for 0x7200000000000001:0x25 service-FID
   Loaded: loaded (/usr/lib/systemd/system/m0d@.service; static; vendor preset: disabled)
   Active: failed (Result: signal) since Thu 2021-06-17 16:34:33 CEST; 1h 33min ago
  Process: 48993 ExecStart=/usr/libexec/cortx-motr/motr-server m0d-%i (code=killed, signal=ABRT)
 Main PID: 48993 (code=killed, signal=ABRT)
Jun 17 16:34:24 sage-tier1-2 motr-server[48993]: motr[48993]:  ab00  ERROR  [ioservice/io_foms.c:2008:indexvec_wire2mem]  <! rc=-2
Jun 17 16:34:24 sage-tier1-2 motr-server[48993]: motr[48993]:  ab00  ERROR  [ioservice/io_foms.c:2008:indexvec_wire2mem]  <! rc=-2
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: motr[48993]:  ab00  ERROR  [ioservice/io_foms.c:2008:indexvec_wire2mem]  <! rc=-2
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: motr[48993]:  a750  FATAL  [lib/assert.c:50:m0_panic]  panic: (stob->so_state != CSS_DELETE) at m0_storage_dev_stob_create() (ioservice/storage_dev.c:822)  [git: sage-base-1.0-389-g09ff618] /var/log/seagate/motr/trace/m0d-0x7200000000000001:0x25/m0trace.48993
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: Motr panic: (stob->so_state != CSS_DELETE) at m0_storage_dev_stob_create() ioservice/storage_dev.c:822 (errno: 0) (last failed: none) [git: sage-base-1.0-389-g09ff618] pid: 48993  /var/log/seagate/motr/trace/m0d-0x7200000000000001:0x25/m0trace.48993
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(m0_arch_backtrace+0x2f)[0x7f1b446f38df]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(m0_arch_panic+0xf3)[0x7f1b446f3ac3]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(+0x34be44)[0x7f1b446e3e44]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(+0x34327d)[0x7f1b446db27d]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(m0_cc_stob_create+0x58)[0x7f1b446d6b98]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(+0x33ef4e)[0x7f1b446d6f4e]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(+0x34016b)[0x7f1b446d816b]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(+0x31fd5b)[0x7f1b446b7d5b]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(m0_thread_trampoline+0x5e)[0x7f1b446ea2ee]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libmotr.so.2(+0x35c82d)[0x7f1b446f482d]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libpthread.so.0(+0x7ea5)[0x7f1b43e81ea5]
Jun 17 16:34:25 sage-tier1-2 motr-server[48993]: /lib64/libc.so.6(clone+0x6d)[0x7f1b42d2996d]
Jun 17 16:34:33 sage-tier1-2 systemd[1]: m0d@0x7200000000000001:0x25.service: main process exited, code=killed, status=6/ABRT
Jun 17 16:34:33 sage-tier1-2 systemd[1]: Unit m0d@0x7200000000000001:0x25.service entered failed state.
Jun 17 16:34:33 sage-tier1-2 systemd[1]: m0d@0x7200000000000001:0x25.service failed.
```

The application was trying to delete the object and then write to it again immediately.

Should we really panic on this cause?

**Comment by andriytk** [comment]
```
(gdb) bt
#0  0x00007f1b42c61387 in raise () from /lib64/libc.so.6
#1  0x00007f1b42c62a78 in abort () from /lib64/libc.so.6
#2  0x00007f1b446f3acd in m0_arch_panic (c=c@entry=0x7f1b44b72c40 <__pctx.18741>, ap=ap@entry=0x7f18f5ffa7c8)
    at lib/user_space/uassert.c:131
#3  0x00007f1b446e3e44 in m0_panic (ctx=ctx@entry=0x7f1b44b72c40 <__pctx.18741>) at lib/assert.c:52
#4  0x00007f1b446db27d in m0_storage_dev_stob_create (devs=0x606958 <instance.22980+18456>, sid=sid@entry=0x7f1672d66f40, 
    dtx=dtx@entry=0x7f1672d67028) at ioservice/storage_dev.c:822
#5  0x00007f1b446d6b98 in m0_cc_stob_create (fom=fom@entry=0x7f1672d66f60, sid=sid@entry=0x7f1672d66f40) at ioservice/cob_foms.c:826
#6  0x00007f1b446d6f4e in cob_stob_create (fom=fom@entry=0x7f1672d66f60, attr=attr@entry=0x7f18f5ffac20) at ioservice/cob_foms.c:516
#7  0x00007f1b446d816b in cob_ops_fom_tick (fom=0x7f1672d66f60) at ioservice/cob_foms.c:776
#8  0x00007f1b446b7d5b in fom_exec (fom=0x7f1672d66f60) at fop/fom.c:791
#9  loc_handler_thread (th=0x1f82af0) at fop/fom.c:931
#10 0x00007f1b446ea2ee in m0_thread_trampoline (arg=arg@entry=0x1f82af8) at lib/thread.c:117
#11 0x00007f1b446f482d in uthread_trampoline (arg=0x1f82af8) at lib/user_space/uthread.c:98
#12 0x00007f1b43e81ea5 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f1b42d2996d in clone () from /lib64/libc.so.6
```

**Comment by andriytk** [comment]
[m0trace.48993.txt.zip](https://github.com/Seagate/cortx-motr/files/6671946/m0trace.48993.txt.zip)

**Comment by andriytk** [comment]
I'm not aware it was investigated and fixed by anyone, so, I'm afraid - yes, probably it's still there.

**Comment by andriytk** [comment]
It still happens:

```
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: motr[75161]:  9810  FATAL  [lib/assert.c:50:m0_panic]  panic: (stob->so_sta
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: Motr panic: (stob->so_state != CSS_DELETE) at m0_storage_dev_stob_create() 
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(m0_arch_backtrace+0x2f)[0x7f9e8210adef]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(m0_arch_panic+0xe5)[0x7f9e8210afc5]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(m0_panic+0x139)[0x7f9e820fb049]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(m0_storage_dev_stob_create+0x116)[0x7f9e820f0556]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(m0_cc_stob_create+0x58)[0x7f9e820ebe28]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(+0x33f202)[0x7f9e820ec202]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(+0x3404ab)[0x7f9e820ed4ab]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(+0x320360)[0x7f9e820cd360]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(m0_thread_trampoline+0x5a)[0x7f9e8210181a]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libmotr.so.2(+0x35ebfd)[0x7f9e8210bbfd]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libpthread.so.0(+0x7ea5)[0x7f9e81896ea5]
Nov 15 20:41:43 sage-tier1-2 motr-server[75161]: /lib64/libc.so.6(clone+0x6d)[0x7f9e8073e96d]
Nov 15 20:41:48 sage-tier1-2 sspl-ll[11693]: INFO RAIDsensor, dir not found: /tmp/dcs/hpi  (raid.py:87)
Nov 15 20:41:48 sage-tier1-2 sspl-ll[11693]: INFO RAIDsensor, rechecking in 10 secs (raid.py:88)
Nov 15 20:41:48 sage-tier1-2 hare-hax[73910]: 2021-11-15 20:41:48,510 [DEBUG] {fs-stats-updater} CACHE: created. fn_name=KVA
Nov 15 20:41:48 sage-tier1-2 hare-hax[73910]: 2021-11-15 20:41:48,510 [DEBUG] {fs-stats-updater} KVGET key=leader, kwargs={}
Nov 15 20:41:50 sage-tier1-2 sspl-ll[11693]: INFO ThreadController, dir not found: /tmp/dcs/hpi  (thread_controller.py:119)
Nov 15 20:41:50 sage-tier1-2 sspl-ll[11693]: INFO ThreadController, rechecking in 10 secs (thread_controller.py:120)
Nov 15 20:41:50 sage-tier1-2 systemd[1]: m0d@0x7200000000000001:0x25.service: main process exited, code=killed, status=6/ABR
Nov 15 20:41:50 sage-tier1-2 systemd[1]: Unit m0d@0x7200000000000001:0x25.service entered failed state.
Nov 15 20:41:50 sage-tier1-2 systemd[1]: m0d@0x7200000000000001:0x25.service failed.
```

**Comment by r-wambui** [comment]
@nkommuri has this been assigned to anyone? could you also update if this is planned for current or future sprints.

**Comment by r-wambui** [comment]
@nikitadanilov could please assign this to someone, or let's know if this need to be added to backlog.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~752267]

Have you seen similar panic in any of the recent core dump issues analyzed by you?

Hi [~934401]

Have we tested similar scenario?
{noformat}
The application was trying to delete the object and then write to it again immediately.
{noformat}

**Comment by cortx-admin** [comment]
> Zoheb Khan commented in Jira Server:

[~530903], As per QA, This has not been tested in R2.

**Comment by chandradharraval** [comment]
Hi @andriytk, @madhavemuri,
Panic here is as per existing design for writing to deleted object. Do we want to change behavior to returning error instead of assert here?

**Comment by andriytk** [comment]
Yes, we better should return an error instead of panic.

**Comment by cortx-admin** [comment]
> Jugal Patil commented in Jira Server:

Issue reproducible by using 2 m0client instances
 instance 1 - deletes obj in background
 instance 2 - writes the same object 

object gets created before delete fom completes

This bug is not reproducible when using s3 as motr fids are not used directly
 For applications that don't use s3 above panic is observed.

**Comment by cortx-admin** [comment]
> Jugal Patil commented in Jira Server:

Issue reproducible using 2 m0clients
client 1 deletes obj in background
client 2 writes same obj 

If application tries to write obj before delete fom completes then above panic is observed

For applications using s3 above panic is not observed as motr fids are not getting used directly.

**Comment by nkommuri** [comment]
> Hi @andriytk, @madhavemuri, Panic here is as per existing design for writing to deleted object. Do we want to change behavior to returning error instead of assert here?

Yes, As per discussion with @madhavemuri  in bug scrub, we need to fix it in motr. motr should not panic. Motr should handle the error gracefully.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

[~752267] - Can you test this issue with latest build(with m0client)?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
